### ISSUE TITLE
Styles on main page

### ISSUE THREAD

**Issue by Tornadosky** [elebitzero/openai-react-chat#159]
Hi! Thanks for the great app. I was trying to get it working on my computer, but it looks a bit different from what is in README, mainly by some styles on the main page.  I wonder if it's because of issues on my side or that in the last commits you did change something?
Here is the screenshot:

![image](https://github.com/elebitzero/openai-react-chat/assets/109428348/a822c56f-cc3b-4d3e-8393-336c6972c02a)

**Comment by elebitzero** [comment]
Hi, thanks for trying out my app! Recently I did some localization changes and bumped a few packages. I tested on Brave, Chrome, Edge, Firefox, and LibreWolf and they all seem good. It could be you have an extension that is toggling to dark theme since it's not fully supported yet.

**Comment by elebitzero** [comment]
Hi @Tornadosky,  I changed my system to 'dark' and I saw the issues you mentioned. I have updated the code to work better in dark mode and I will be adding a user preference for the theme with the choices of dark, light, or system.
